In [16]:
import pandas as pd
import numpy as np


data = pd.read_csv('C:\Hari\Work\Data analysis projects\Premier league\PremierLeagueMatches.csv')
data1 = data.iloc[:, :-1]
data1

,Matchday,Date,Time,Home Team,homeScore,homeXG,awayScore,awayXG,Away Team,Attendance,Referee,Stadium,Result
0,1,2022-08-05,20:00,Crystal Palace,0.0,1.2,2.0,1.0,Arsenal,"25,286",Anthony Taylor,Selhurst Park,A
1,1,2022-08-06,12:30,Fulham,2.0,1.2,2.0,1.2,Liverpool,"22,207",Andy Madley,Craven Cottage,D
2,1,2022-08-06,15:00,Tottenham,4.0,1.5,1.0,0.5,Southampton,"61,732",Andre Marriner,Tottenham Hotspur Stadium,H
3,1,2022-08-06,15:00,Newcastle Utd,2.0,1.7,0.0,0.3,Nott'ham Forest,"52,245",Simon Hooper,St James' Park,H
4,1,2022-08-06,15:00,Leeds United,2.0,0.8,1.0,1.3,Wolves,"36,347",Robert Jones,Elland Road,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,38,2025-05-25,16:00,Fulham,NaN,NaN,NaN,NaN,Manchester City,NaN,NaN,Craven Cottage,NaN
1136,38,2025-05-25,16:00,Nott'ham Forest,NaN,NaN,NaN,NaN,Chelsea,NaN,NaN,The City Ground,NaN
1137,38,2025-05-25,16:00,Manchester Utd,NaN,NaN,NaN,NaN,Aston Villa,NaN,NaN,Old Trafford,NaN
1138,38,2025-05-25,16:00,Wolves,NaN,NaN,NaN,NaN,Brentford,NaN,NaN,Molineux Stadium,NaN
1139,38,2025-05-25,16:00,Tottenham,NaN,NaN,NaN,NaN,Brighton,NaN,NaN,Tottenham Hotspur Stadium,NaN

In [26]:
data1.drop_duplicates
data1.dropna (inplace = True) 
data1.rename(columns = {'Home Team': 'Home_team', 'Away Team':'Away_team'}, inplace=True)
data1

,Matchday,Date,Time,Home_team,homeScore,homeXG,awayScore,awayXG,Away_team,Attendance,Referee,Stadium,Result
0,1,2022-08-05,20:00,Crystal Palace,0.0,1.2,2.0,1.0,Arsenal,"25,286",Anthony Taylor,Selhurst Park,A
1,1,2022-08-06,12:30,Fulham,2.0,1.2,2.0,1.2,Liverpool,"22,207",Andy Madley,Craven Cottage,D
2,1,2022-08-06,15:00,Tottenham,4.0,1.5,1.0,0.5,Southampton,"61,732",Andre Marriner,Tottenham Hotspur Stadium,H
3,1,2022-08-06,15:00,Newcastle Utd,2.0,1.7,0.0,0.3,Nott'ham Forest,"52,245",Simon Hooper,St James' Park,H
4,1,2022-08-06,15:00,Leeds United,2.0,0.8,1.0,1.3,Wolves,"36,347",Robert Jones,Elland Road,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042,29,2025-03-15,15:00,Ipswich Town,2.0,0.4,4.0,1.5,Nott'ham Forest,"29,878",Michael Salisbury,Portman Road Stadium,A
1044,29,2025-03-15,15:00,Southampton,1.0,1.3,2.0,0.4,Wolves,"30,950",Robert Jones,St Mary's Stadium,A
1045,29,2025-03-15,17:30,Bournemouth,1.0,1.6,2.0,0.8,Brentford,"11,180",Craig Pawson,Vitality Stadium,A
1046,29,2025-03-16,13:30,Arsenal,1.0,0.7,0.0,0.4,Chelsea,"60,311",Chris Kavanagh,Emirates Stadium,H
1047,29,2025-03-16,13:30,Fulham,2.0,1.0,0.0,0.9,Tottenham,"27,182",Andy Madley,Craven Cottage,H

In [ ]:
#Total Home and away goals per team

total_home_goals_by_team = data1.groupby('Home_team')['homeScore'].sum()
print(total_home_goals_by_team.head(10))

total_away_goals_by_team = data1.groupby('Away_team')['awayScore'].sum()
total_away_goals_by_team.head(10)

Home_team
Arsenal           129.0
Aston Villa       104.0
Bournemouth        65.0
Brentford          94.0
Brighton           88.0
Burnley            19.0
Chelsea            91.0
Crystal Palace     75.0
Everton            58.0
Fulham             84.0
Name: homeScore, dtype: float64

Away_team
Arsenal           103.0
Aston Villa        62.0
Bournemouth        74.0
Brentford          70.0
Brighton           84.0
Burnley            22.0
Chelsea            77.0
Crystal Palace     58.0
Everton            47.0
Fulham             69.0
Name: awayScore, dtype: float64

In [ ]:
#Total goals by teams by season